title: Research Opportunity Success System (ROSS)
description: 
theme: just-the-docs

aux_links:
  GitHub Repository: https://github.com/yanyan-dong/ross
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

nav:
  - title: "Funding Opportunities"
    url: "/"
  - title: "Opportunities Based on Interest"
    url: "/cus/"
